/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:44597fc4-8123-486b-979f-24350ce27f18",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_LIT9fRNim",
    "aws_user_pools_web_client_id": "41t8cr8oac7u29rvg38dcke6pi",
    "oauth": {},
    "aws_cognito_login_mechanisms": [
        "PREFERRED_USERNAME"
    ],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://cnw6nrrngjcmndr5wb5o7yqota.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-ecul3bw4qnc6rg7tlkfvyash7e",
    "aws_user_files_s3_bucket": "amplifyapp3ff7bee2b3fc41e8882542819c1a8ade151551-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
